---
startTime: "30"
gameTime: "600"
restartTime: "20"
playersPerTeam: "2"
level: "EggWars"
teams:
  red:
    players: []
    color: "ยง4"
    spawn: []

  blue:
    players: []
    color: "ยง9"
    spawn: []
...